### ISSUE TITLE
CanopyTax npm publish access

### ISSUE THREAD

**Issue by parkm** [CanopyTax/bandicoot#110]
@joeldenning Hey Joel! From what I can tell it looks like you have access to the npm package for bandicoot https://www.npmjs.com/package/bandicoot We were hoping have the CanopyTax group added as a collaborator to let us publish new versions. Thanks!

**Comment by internettrans** [comment]
Sure, I'm happy to give you access. I'm not sure how to give a group access to a package - all that I've seen is that an npm organization has access to the packages under that npm scope. For example, `@canopytax/styleguide` is under the `@canopytax/` npm scope, so the people in the canopytax org have publish access. But since `bandicoot` is not under the canopytax scope, you don't have access and I don't think it's possible for me to give access to the whole group. If I'm missing something, let me know. Otherwise, I'm happy to give you access individually if you provide me a list of npm usernames. Is parkm your username on npm? Anyone else I should give access to?

**Comment by parkm** [comment]
Oh okay I wasn't sure if you were able to add an organization or not, but adding individual access works! Here's the list of npm usernames we'd like added:
`parkm` 
`greenjeffreym` Jeff Green
`rchilds` Rhys Childs
`ron.douglas` Ron Douglas
`tannerrigby` Tanner Rigby
`geoctrl` Tony Lefler

**Comment by internettrans** [comment]
Done via `npm owner add parkm bandicoot` (repeated for each person)

**Comment by parkm** [comment]
Thanks Joel! Looks like `geoctrl` was the only one that stuck, but Tony was able to get me added at that point
