### ISSUE TITLE
Tab key

### ISSUE THREAD

**Issue by dvnrsn** [CanopyTax/bandicoot#49]
Context: Lists
Pressing the tab key fails to indent in Chrome and simply exits the contentEditable element in Safari/Firefox

**Comment by internettrans** [comment]
This is a decision I made consciously when I implemented bandicoot. My understanding is that hijacking the tab key is one of the worst things you can do for keyboard and screenreader accessibility, because a keyboard user will be forever stuck inside the rich text editor once they are in it.

There might be more to this that I'm unaware of, but that's the reason for this. I'm open to discussing options that would allow tab key to work without sacrificing accessibility

**Comment by jairuzu** [comment]
I agree with Joel on this from the accessibility standpoint.  `tab` is the way keyboard users navigate through tabbable items on the page.  I don't think we want to override its default behavior unless we get fancy and give them away to opt out of it once they are stuck in it which could potentially be confusing in its own right.

**Comment by internettrans** [comment]
@dvnrsn can you think of a way of doing this without sacrificing accessibility? What I have been doing is adding indent and outdent control buttons to the rich text editor.

**Comment by dvnrsn** [comment]
I am in agreement. Didn't think about tabbing out. Will need to implement buttons with `execCommand('indent') outdent`
Making issue for docs and closing this one
